version: 2
jobs:
    build:
        docker:
            - {image: 'circleci/android:api-27-node'}
        working_directory: ~/repo
        environment:
            JVM_OPTS: '-Xmx3200m'
        steps:
            - checkout
            - {run: {name: 'Install gradle', command: "wget https://services.gradle.org/distributions/gradle-4.0.2-bin.zip -P /tmp\nsudo unzip -d /opt/gradle /tmp/gradle-*.zip\necho 'export GRADLE_HOME=/opt/gradle/gradle-4.0.2' >> $BASH_ENV\necho 'export PATH=$PATH:/opt/gradle/gradle-4.0.2/bin' >> $BASH_ENV\nsource $BASH_ENV\n"}}
            - {run: {name: 'Install ionic and cordova', command: "sudo npm install -g ionic cordova yarn\n"}}
            - {run: {name: 'Install npm packages', command: "yarn install\n"}}
            - {run: {name: 'Install Cordova plugins and add android platform', command: "ionic cordova platform add android --noresources\nionic config set -g telemetry true\n"}}
            - {run: {name: 'Generate apk', command: "ionic cordova build android --verbose\nmkdir -p /tmp/apk\ncp -r platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/apk\n"}}
            - {store_artifacts: {path: /tmp/apk, destination: apks}}
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
